## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
!pip install gmaps

Requirement already satisfied: gmaps in c:\users\tahira\anaconda3\lib\site-packages (0.9.0)
Requirement already satisfied: geojson>=2.0.0 in c:\users\tahira\anaconda3\lib\site-packages (from gmaps) (2.5.0)
Requirement already satisfied: ipywidgets>=7.0.0 in c:\users\tahira\anaconda3\lib\site-packages (from gmaps) (7.6.3)
Requirement already satisfied: six in c:\users\tahira\anaconda3\lib\site-packages (from gmaps) (1.15.0)
Requirement already satisfied: ipython>=5.3.0 in c:\users\tahira\anaconda3\lib\site-packages (from gmaps) (7.20.0)
Requirement already satisfied: traitlets>=4.3.0 in c:\users\tahira\anaconda3\lib\site-packages (from gmaps) (5.0.5)
Requirement already satisfied: setuptools>=18.5 in c:\users\tahira\anaconda3\lib\site-packages (from ipython>=5.3.0->gmaps) (52.0.0.post20210125)
Requirement already satisfied: colorama in c:\users\tahira\anaconda3\lib\site-packages (from ipython>=5.3.0->gmaps) (0.4.4)
Requirement already satisfied: pickleshare in c:\users\tahira\anaconda3\lib\site-packages (from ipython>=5.3.0->gmaps) (0.7.5)
Requirement already satisfied: decorator in c:\users\tahira\anaconda3\lib\site-packages (from ipython>=5.3.0->gmaps) (4.4.2)
Requirement already satisfied: backcall in c:\users\tahira\anaconda3\lib\site-packages (from ipython>=5.3.0->gmaps) (0.2.0)
Requirement already satisfied: pygments in c:\users\tahira\anaconda3\lib\site-packages (from ipython>=5.3.0->gmaps) (2.7.4)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\tahira\anaconda3\lib\site-packages (from ipython>=5.3.0->gmaps) (3.0.8)
Requirement already satisfied: jedi>=0.16 in c:\users\tahira\anaconda3\lib\site-packages (from ipython>=5.3.0->gmaps) (0.17.2)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in c:\users\tahira\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (1.0.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\users\tahira\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (3.5.1)
Requirement already satisfied: ipykernel>=4.5.1 in c:\users\tahira\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (5.3.4)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\tahira\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->gmaps) (5.1.2)
Requirement already satisfied: tornado>=4.2 in c:\users\tahira\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.1)
Requirement already satisfied: jupyter-client in c:\users\tahira\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.1.7)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in c:\users\tahira\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=5.3.0->gmaps) (0.7.0)
Requirement already satisfied: jupyter-core in c:\users\tahira\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.7.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\tahira\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (3.2.0)
Requirement already satisfied: ipython-genutils in c:\users\tahira\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (0.2.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\tahira\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (20.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\tahira\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (0.17.3)
Requirement already satisfied: wcwidth in c:\users\tahira\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->gmaps) (0.2.5)
Requirement already satisfied: notebook>=4.4.1 in c:\users\tahira\anaconda3\lib\site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (6.2.0)
Requirement already satisfied: nbconvert in c:\users\tahira\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (6.0.7)
Requirement already satisfied: prometheus-client in c:\users\tahira\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.9.0)
Requirement already satisfied: terminado>=0.8.3 in c:\users\tahira\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.9.2)
Requirement already satisfied: Send2Trash>=1.5.0 in c:\users\tahira\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.5.0)
Requirement already satisfied: argon2-cffi in c:\users\tahira\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (20.1.0)
Requirement already satisfied: jinja2 in c:\users\tahira\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.11.3)
Requirement already satisfied: pyzmq>=17 in c:\users\tahira\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (20.0.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\tahira\anaconda3\lib\site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (2.8.1)
Requirement already satisfied: pywin32>=1.0 in c:\users\tahira\anaconda3\lib\site-packages (from jupyter-core->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (227)
Requirement already satisfied: pywinpty>=0.5 in c:\users\tahira\anaconda3\lib\site-packages (from terminado>=0.8.3->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.7)
Requirement already satisfied: cffi>=1.0.0 in c:\users\tahira\anaconda3\lib\site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.14.5)
Requirement already satisfied: pycparser in c:\users\tahira\anaconda3\lib\site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.20)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\tahira\anaconda3\lib\site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.1.1)
Requirement already satisfied: defusedxml in c:\users\tahira\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.6.0)
Requirement already satisfied: testpath in c:\users\tahira\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.4.4)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\tahira\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.1)
Requirement already satisfied: bleach in c:\users\tahira\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (3.3.0)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\tahira\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.3)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\tahira\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.4.3)
Requirement already satisfied: jupyterlab-pygments in c:\users\tahira\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.1.2)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\tahira\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.8.4)
Requirement already satisfied: nest-asyncio in c:\users\tahira\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.4.2)
Requirement already satisfied: async-generator in c:\users\tahira\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.10)
Requirement already satisfied: packaging in c:\users\tahira\anaconda3\lib\site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (20.9)
Requirement already satisfied: webencodings in c:\users\tahira\anaconda3\lib\site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.1)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\tahira\anaconda3\lib\site-packages (from packaging->bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.4.7)

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [3]:
# Use ../Weather... to go up one folder to find the correct information instead of looking for one doc. (. the folder you're in, ..the folder before)

In [4]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,esperance,-33.8667,121.9000,75.20,33,46,12.66,AU,2021-03-15 06:07:58
1,1,weyburn,49.6668,-103.8511,33.80,37,95,18.41,CA,2021-03-15 06:15:08
2,2,cape town,-33.9258,18.4232,62.01,94,90,17.27,ZA,2021-03-15 06:05:21
3,3,rio gallegos,-51.6226,-69.2181,48.20,87,0,5.75,AR,2021-03-15 06:09:12
4,4,cherskiy,68.7500,161.3000,-14.01,94,63,5.08,RU,2021-03-15 06:08:07

In [5]:
# 2. Prompt the user to enter minimum and maximum temperature criteria

In [6]:
# Minimum temperature 75, Maximum temperature 90
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [7]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
# (6.5.3)

In [8]:
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,esperance,-33.8667,121.9000,75.20,33,46,12.66,AU,2021-03-15 06:07:58
6,6,souillac,-20.5167,57.5167,77.00,94,75,5.75,MU,2021-03-15 06:07:35
7,7,bubaque,11.2833,-15.8333,78.19,60,0,7.67,GW,2021-03-15 06:08:37
9,9,corowa,-36.0333,146.3833,75.99,29,31,3.00,AU,2021-03-15 06:15:40
14,14,kavieng,-2.5744,150.7967,81.66,81,94,10.38,PG,2021-03-15 06:07:37
16,16,isangel,-19.5500,169.2667,79.12,78,82,6.04,VU,2021-03-15 06:08:36
17,17,avarua,-21.2078,-159.7750,80.60,83,20,2.30,CK,2021-03-15 06:08:15
19,19,kupang,-10.1667,123.5833,86.00,79,40,9.22,ID,2021-03-15 06:15:42
20,20,busselton,-33.6500,115.3333,82.00,33,37,5.01,AU,2021-03-15 06:07:28
22,22,charters towers,-20.1000,146.2667,88.66,42,23,10.92,AU,2021-03-15 06:15:43

In [9]:
# 4a. Determine if there are any empty rows (null values).
# Use ".count()" to determine if there are any null values.
preferred_cities_df.count()

City_ID       177
City          177
Lat           177
Lng           177
Max Temp      177
Humidity      177
Cloudiness    177
Wind Speed    177
Country       176
Date          177
dtype: int64

In [10]:
# 4b. Drop any empty rows (null values) and create a new DataFrame that doesn’t have empty rows.
# Use ".dropna()" method to drop null values
clean_df=preferred_cities_df.dropna()

In [11]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

               City Country  Max Temp      Lat       Lng Hotel Name
0         esperance      AU     75.20 -33.8667  121.9000
6          souillac      MU     77.00 -20.5167   57.5167
7           bubaque      GW     78.19  11.2833  -15.8333
9            corowa      AU     75.99 -36.0333  146.3833
14          kavieng      PG     81.66  -2.5744  150.7967
16          isangel      VU     79.12 -19.5500  169.2667
17           avarua      CK     80.60 -21.2078 -159.7750
19           kupang      ID     86.00 -10.1667  123.5833
20        busselton      AU     82.00 -33.6500  115.3333
22  charters towers      AU     88.66 -20.1000  146.2667

In [12]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = "Hotels"
hotel_df.head(10)

# (6.5.4)

               City Country  Max Temp      Lat       Lng Hotel Name
0         esperance      AU     75.20 -33.8667  121.9000     Hotels
6          souillac      MU     77.00 -20.5167   57.5167     Hotels
7           bubaque      GW     78.19  11.2833  -15.8333     Hotels
9            corowa      AU     75.99 -36.0333  146.3833     Hotels
14          kavieng      PG     81.66  -2.5744  150.7967     Hotels
16          isangel      VU     79.12 -19.5500  169.2667     Hotels
17           avarua      CK     80.60 -21.2078 -159.7750     Hotels
19           kupang      ID     86.00 -10.1667  123.5833     Hotels
20        busselton      AU     82.00 -33.6500  115.3333     Hotels
22  charters towers      AU     88.66 -20.1000  146.2667     Hotels

In [13]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url="https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    # NOTE: Can add the parameters as a dictionary of strings using the "params" keyword arguament requests.get{'base URL', params=parameteres}
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first "hotel" from the "results" and store the "name", if a hotel isn't found "skip" the city. (Use Try, Except).
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        found=hotels["results"][0]["name"]
        print(f"{found} Is Found.")
        
    except (IndexError):
        print("Hotel Is Not Found... Skipping")
    
    
    # (6.5.4)

Hospitality Esperance Is Found.
Shanti Maurice Resort & Spa Is Found.
Casa Dora, Bubaque Is Found.
Statesman Motor Inn Is Found.
Nusa Island Retreat Is Found.
Volcano Sea View Tree House Is Found.
Paradise Inn Is Found.
Hotel On The Rock by Prasanthi Is Found.
Observatory Guest House Is Found.
Cattleman's Rest Motor Inn Is Found.
Casa Tia Villa Is Found.
Keleti Beach Resort Is Found.
Pension Maro'i Is Found.
Hotel El Emigrante Is Found.
Sharif Plaza Hotel Is Found.
Atrium Hotel Mandurah Is Found.
Grage Hotel Bengkulu Is Found.
Shangping Shuyuan Inn Is Found.
Gîte kajeon Is Found.
Pousada 100 Passos Is Found.
Hôtel & Restaurant DIANA Ambilobe Is Found.
ibis Styles Mt Isa Verona Is Found.
Grand Vilia Hotel Is Found.
温州喜来登酒店 Is Found.
Aldea del Bazar Hotel and Spa Is Found.
Tour Eiffel Hotel Benin Is Found.
Finch Bay Galapagos Hotel Is Found.
Sunset Inn Is Found.
Pereybere Hotel & Spa Is Found.
Pousada Porto Praia Is Found.
Isles Sunset Lodge Is Found.
Al-bustan Hotel And Restaurant. Is Found.
Hotel Memory Is Found.
Mini Hotel Central Is Found.
BON Hotel Waterfront Richards Bay Is Found.
Chambres d'hôte "La Trinité" Is Found.
Lindsey Hôtel Is Found.
ZINGARA 76ft Catamaran, full crew-all included Is Found.
Nathaniel's Lodge Is Found.
Minshuku Agaihama Is Found.
Shandrani Beachcomber Resort & Spa Is Found.
The Espiritu Hotel Is Found.
Guayacan Real Is Found.
Hotel Archipelago Is Found.
Lorengau Harbourside Hotel Is Found.
Poro Beach Is Found.
Hotel Kununurra Is Found.
Orient Apartments Is Found.
Butterfly Beach Hotel Is Found.
Gite de la RYAWA Is Found.
Villa Bella Is Found.
Piaçabuçu News Is Found.
La Villa Mahatsara Is Found.
Taloa Heights Is Found.
Screensaver Is Found.
Beira Terrace Hotel Is Found.
Hotel Playa Bonita Is Found.
Atlantis Hotel Is Found.
Bora-Bora Pearl Beach Resort & Spa Is Found.
Hotel Olako Is Found.
Scoop Guest House Is Found.
Imam Family Is Found.
Bonthe Holiday Village Is Found.
castelo pizzaria Is Found.
HAMDAN PLAZA HOTEL SALALAH Is Found.
Hospitality Carnarvon Is Found.
Hotel Fajar Is Found.
Restaurant Plazza Hotel Is Found.
LANDU MARINEZA LUFUANDU TONI Is Found.
Hotel Edi Is Found.
SEGAYA PROPERTY Is Found.
Hotels in Lakshadweep Islands Is Found.
Purnama Hotel Is Found.
Hotel Santika Luwuk Is Found.
Pension Oaoa Is Found.
Hotel Is Not Found... Skipping
Quality Suites Vila Velha Is Found.
Emeraude Beach Attitude Hotel Is Found.
Tanjung Kodok Beach Resort Is Found.
Hotel Citra Is Found.
NORTHVIEW Hotel Is Found.
Hotel The Royal Honours Is Found.
Lambitu Hotel Is Found.
Kost Pria Is Found.
Dena Hotel Is Found.
Niyama Private Islands Maldives Is Found.
Lazy River Motor Inn Is Found.
Namatanai Hotel Is Found.
Ekanta Hotel Pvt. Ltd Is Found.
Welcomhotel Bay Island Port Blair Is Found.
Villa Mar Colina Is Found.
OYO Pousada Horizonte Is Found.
Tianlun Tanxianglou Hotel Is Found.
Villa Enata Is Found.
Tu Casa Is Found.
Hotel Grand Chancellor Launceston Is Found.
Hotel Is Not Found... Skipping
Bungalow 63 Is Found.
Khách Sạn Thương Mại Is Found.
La Caz Oceane Is Found.
Paradise Hotel Is Found.
Hotel Is Not Found... Skipping
Hôtel Le Dronmi Is Found.
OYO 598 Peony Hotel Is Found.
Sea Lounge! Bar, Club & Restaurant Is Found.
Boyue boutique Hotel Is Found.
Banjanay Hotel Is Found.
Nuli Sapi Is Found.
ALETHEIA Appartement Sinnamary Is Found.
Aipana Plaza Hotel Is Found.
Big Daddy's Beach Club & Hotel Is Found.
CeBlue Villas & Beach Resort Is Found.
Posada Lilia Is Found.
Amaloh Boutique Resort Is Found.
Relax Inn Hotel Is Found.
Hôtel Le Lagon Is Found.
Penginapan Kim Is Found.
RedDoorz Syariah near Taman Berlabuh Tarakan Is Found.
Hotel Is Not Found... Skipping
Swiss Belhotel Manokwari Is Found.
Hotel Kou-Bugny Is Found.
Makkah Clock Royal Tower, A Fairmont Hotel Is Found.
JABIR HOTEL Is Found.
Murshida & Zakir's Nest Is Found.
SanBiz Lodge Is Found.
Hotel Narayan Avezika Comfort Is Found.
Auki Motel Is Found.
RH HOTEL (4 Star) Is Found.
Hotel Panorama Is Found.
Hotel Albergue de Olinda Is Found.
Fengshui Residence Is Found.
Hotel Is Not Found... Skipping
Nacala Plaza Business Design Hotel Is Found.
Hotel Victoria Is Found.
Oceano Is Found.
Veranda Paul et Virginie Hotel & Spa Is Found.
Hotel Saigon-PT Is Found.
Pousada Guará's Is Found.
Moon light Furnished Units Is Found.
Khách sạn Sài Gòn Bạc Liêu Is Found.
Hotel Mout View Is Found.
Hotel Is Not Found... Skipping
Salinas do Maragogi All Inclusive Resort Is Found.
Hotel Is Not Found... Skipping
Dibbo areaمنطقة دبو Is Found.
Daru Lodge Is Found.
Kirari Guest House Is Found.
Mercure Belém Boulevard Hotel Is Found.
Hotel RIKMAN Continental Is Found.
Maitai Lapita Village Huahine Is Found.
Heritage Park Hotel Is Found.
Agan-Hotel Is Found.
OYO 3114 Homestay Dalimo Is Found.
Hotel Praia Morena Is Found.
Le Rocher de Tahiti Is Found.
Guest House HESADA Is Found.
The Hotel Shamrock Is Found.
Mashida Guest House Is Found.
Mercure Padang Is Found.
Tinaya Treats Is Found.
Guest Hotel Is Found.
Huadu Hotel Is Found.
Conrad Bora Bora Nui Is Found.
Phama Lodge Is Found.
Le gîte du Koniambo Is Found.
Tamir Hotel Ltd Is Found.
Vahmoneh Lodge Vanimo Is Found.
Hotel Is Not Found... Skipping
安琪酒店 Is Found.
Hotel Atoll Emerald Miyakojima Is Found.
Groote Eylandt Lodge Is Found.
Kos Bu Haji Mblumbang Is Found.
Melia Coco Beach Is Found.
Villa Park Hotel | Natal Is Found.
Will T Place Is Found.
The Passage Samui Villas & Resort, Thailand Is Found.

In [14]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df=hotel_df.dropna() 

# EXAMPLE: if lines 7 and 13 [7, 13]
#hotel_list_df = hotel_df.drop[]

In [15]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [16]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<d1>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Max Temp} ℉</dd>
</d1>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
clean_hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [17]:
# 11a. Add a marker layer for each city to the map. (6.5.4)

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.3)
heat_layer = gmaps.heatmap_layer(locations, dissipating=False,
            max_intensity=300, point_radius=4)

marker_layer = gmaps.marker_layer(locations, info_box_content=clean_hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))